CREATE TABLE mw_ckd_followup (
  ckd_followup_visit_id 	int NOT NULL AUTO_INCREMENT,
  patient_id 			int NOT NULL,
  visit_date 			date DEFAULT NULL,
  location 			varchar(255) DEFAULT NULL,
  height 			int DEFAULT NULL,
  weight 			int DEFAULT NULL,
  bp_systolic 			int DEFAULT NULL,
  bp_diastolic 		int DEFAULT NULL,
  heart_rate 			int DEFAULT NULL,
  creatinine 			int DEFAULT NULL,
  gfr 				int DEFAULT NULL,
  urine_protein 		varchar(255) DEFAULT NULL,
  confusion 			varchar(255) DEFAULT NULL,
  fatigue 			varchar(255) DEFAULT NULL,
  nausea 			varchar(255) DEFAULT NULL,
  anorexia 			varchar(255) DEFAULT NULL,
  pruritus 			varchar(255) DEFAULT NULL,
  conjunctiva			varchar(255) DEFAULT NULL,
  ascites 			varchar(255) DEFAULT NULL,
  oedema 			varchar(255) DEFAULT NULL,
  other_symptoms 		varchar(255) DEFAULT NULL,
  ckd_stage 			varchar(255) DEFAULT NULL,
  nsaid_use 			varchar(255) DEFAULT NULL,
  alcohol 			varchar(255) DEFAULT NULL,
  tobacco 			varchar(255) DEFAULT NULL,
  diuretic_hctz 		varchar(255) DEFAULT NULL,
  diuretic_hctz_dose		INT,
  diuretic_hctz_dosing_unit VARCHAR(50),
  diuretic_hctz_route		VARCHAR(50),
  diuretic_hctz_frequency		VARCHAR(50),
  diuretic_hctz_duration   INT,
  diuretic_hctz_duration_units  VARCHAR(50),
  diuretic_furo 		varchar(255) DEFAULT NULL,
  diuretic_furp_dose		INT,
  diuretic_furp_dosing_unit VARCHAR(50),
  diuretic_furp_route		VARCHAR(50),
  diuretic_furp_frequency		VARCHAR(50),
  diuretic_furp_duration   INT,
  diuretic_furp_duration_units  VARCHAR(50),
  diuretic_spiro 		varchar(255) DEFAULT NULL,
  diuretic_spiro_dose		INT,
  diuretic_spiro_dosing_unit VARCHAR(50),
  diuretic_spiro_route		VARCHAR(50),
  diuretic_spiro_frequency		VARCHAR(50),
  diuretic_spiro_duration   INT,
  diuretic_spiro_duration_units  VARCHAR(50),
  ace_i_enal				 			VARCHAR(50),
  ace_i_enal_dose		INT,
  ace_i_enal_dosing_unit VARCHAR(50),
  ace_i_enal_route		VARCHAR(50),
  ace_i_enal_frequency		VARCHAR(50),
  ace_i_enal_duration   INT,
  ace_i_enal_duration_units  VARCHAR(50),
  ace_i_capt				 			VARCHAR(50),
  ace_i_capt_dose		INT,
  ace_i_capt_dosing_unit VARCHAR(50),
  ace_i_capt_route		VARCHAR(50),
  ace_i_capt_frequency		VARCHAR(50),
  ace_i_capt_duration   INT,
  ace_i_capt_duration_units  VARCHAR(50),
  ace_i_lisin			 				VARCHAR(50),
  ace_i_lisin_dose		INT,
  ace_i_lisin_dosing_unit VARCHAR(50),
  ace_i_lisin_route		VARCHAR(50),
  ace_i_lisin_frequency		VARCHAR(50),
  ace_i_lisin_duration   INT,
  ace_i_lisin_duration_units  VARCHAR(50),
  bb_aten				 			VARCHAR(50),
  bb_aten_dose		INT,
  bb_aten_dosing_unit VARCHAR(50),
  bb_aten_route		VARCHAR(50),
  bb_aten_frequency		VARCHAR(50),
  bb_aten_duration   INT,
  bb_aten_duration_units  VARCHAR(50),
  bb_bis				 			VARCHAR(50),
  bb_bis_dose		INT,
  bb_bis_dosing_unit VARCHAR(50),
  bb_bis_route		VARCHAR(50),
  bb_bis_frequency		VARCHAR(50),
  bb_bis_duration   INT,
  bb_bis_duration_units  VARCHAR(50),
  bb_prop				 			VARCHAR(50),
  bb_prop_dose		INT,
  bb_prop_dosing_unit VARCHAR(50),
  bb_prop_route		VARCHAR(50),
  bb_prop_frequency		VARCHAR(50),
  bb_prop_duration   INT,
  bb_prop_duration_units  VARCHAR(50),
  ccb_aml				 			VARCHAR(50),
  ccb_aml_dose		INT,
  ccb_aml_dosing_unit VARCHAR(50),
  ccb_aml_route		VARCHAR(50),
  ccb_aml_frequency		VARCHAR(50),
  ccb_aml_duration   INT,
  ccb_aml_duration_units  VARCHAR(50),
  ccb_nif				 			VARCHAR(50),
  ccb_nif_dose		INT,
  ccb_nif_dosing_unit VARCHAR(50),
  ccb_nif_route		VARCHAR(50),
  ccb_nif_frequency		VARCHAR(50),
  ccb_nif_duration   INT,
  ccb_nif_duration_units  VARCHAR(50),
  other_medications 		varchar(255) DEFAULT NULL,
  took_medications_today 	varchar(255) DEFAULT NULL,
  diet_recommendations 	varchar(255) DEFAULT NULL,
  next_appointment_date	date DEFAULT NULL,
  PRIMARY KEY (ckd_followup_visit_id)
);
