CREATE TABLE mw_chf_followup (
  chf_followup_visit_id 			int NOT NULL AUTO_INCREMENT,
  patient_id 					int NOT NULL,
  visit_date 					date DEFAULT NULL,
  location 					varchar(50) DEFAULT NULL,
  height 					int DEFAULT NULL,	
  weight 					int DEFAULT NULL,
  weight_change 				varchar(50) DEFAULT NULL,
  bp_systolic 					int DEFAULT NULL,
  bp_diastolic 				int DEFAULT NULL,
  heart_rate 					int DEFAULT NULL,
  spo2 					int DEFAULT NULL,
  orthopnea 					varchar(50) DEFAULT NULL,
  dyspnea_on_exertion 				varchar(50) DEFAULT NULL,
  dry_cough 					varchar(50) DEFAULT NULL,
  fatigue			 		varchar(50) DEFAULT NULL,
  hospitalized_since_last_visit_for_ncd 	varchar(50) DEFAULT NULL,
  oedema 					varchar(50) DEFAULT NULL,
  bibasilar_crackles 				varchar(50) DEFAULT NULL,
  jvp_elevated 				varchar(50) DEFAULT NULL,
  volume_status 				varchar(50) DEFAULT NULL,
  nyha_stage 					varchar(50) DEFAULT NULL,
  alcohol 					varchar(50) DEFAULT NULL,
  tobacco 					varchar(50) DEFAULT NULL,
  salt_or_fluid_restricted 			varchar(50) DEFAULT NULL,
  concern_for_depression_or_anxiety 		varchar(50) DEFAULT NULL,
  aspirin 					varchar(50) DEFAULT NULL,
  asprin_asa_dose		INT,
  asprin_asa_dosing_unit varchar(50),
  asprin_asa_route		varchar(50),
  asprin_asa_frequency		varchar(50),
  asprin_asa_duration   INT,
  asprin_asa_duration_units  varchar(50),
  diuretic_hctz 				varchar(50) DEFAULT NULL,
  diuretic_hctz_dose		INT,
  diuretic_hctz_dosing_unit varchar(50),
  diuretic_hctz_route		varchar(50),
  diuretic_hctz_frequency		varchar(50),
  diuretic_hctz_duration   INT,
  diuretic_hctz_duration_units  varchar(50),
  diuretic_furo 				varchar(50) DEFAULT NULL,
  diuretic_furp_dose		INT,
  diuretic_furp_dosing_unit varchar(50),
  diuretic_furp_route		varchar(50),
  diuretic_furp_frequency		varchar(50),
  diuretic_furp_duration   INT,
  diuretic_furp_duration_units  varchar(50),
  diuretic_spiro			 			varchar(50),
  diuretic_spiro_dose		INT,
  diuretic_spiro_dosing_unit varchar(50),
  diuretic_spiro_route		varchar(50),
  diuretic_spiro_frequency		varchar(50),
  diuretic_spiro_duration   INT,
  diuretic_spiro_duration_units  varchar(50),
  ace_i_enal				 			varchar(50),
  ace_i_enal_dose		INT,
  ace_i_enal_dosing_unit varchar(50),
  ace_i_enal_route		varchar(50),
  ace_i_enal_frequency		varchar(50),
  ace_i_enal_duration   INT,
  ace_i_enal_duration_units  varchar(50),
  ace_i_capt				 			varchar(50),
  ace_i_capt_dose		INT,
  ace_i_capt_dosing_unit varchar(50),
  ace_i_capt_route		varchar(50),
  ace_i_capt_frequency		varchar(50),
  ace_i_capt_duration   INT,
  ace_i_capt_duration_units  varchar(50),
  ace_i_lisin			 				varchar(50),
  ace_i_lisin_dose		INT,
  ace_i_lisin_dosing_unit varchar(50),
  ace_i_lisin_route		varchar(50),
  ace_i_lisin_frequency		varchar(50),
  ace_i_lisin_duration   INT,
  ace_i_lisin_duration_units  varchar(50),
  bb_aten				 			varchar(50),
  bb_aten_dose		INT,
  bb_aten_dosing_unit varchar(50),
  bb_aten_route		varchar(50),
  bb_aten_frequency		varchar(50),
  bb_aten_duration   INT,
  bb_aten_duration_units  varchar(50),
  bb_bis				 			varchar(50),
  bb_bis_dose		INT,
  bb_bis_dosing_unit varchar(50),
  bb_bis_route		varchar(50),
  bb_bis_frequency		varchar(50),
  bb_bis_duration   INT,
  bb_bis_duration_units  varchar(50),
  bb_prop				 			varchar(50),
  bb_prop_dose		INT,
  bb_prop_dosing_unit varchar(50),
  bb_prop_route		varchar(50),
  bb_prop_frequency		varchar(50),
  bb_prop_duration   INT,
  bb_prop_duration_units  varchar(50),
  ccb_aml				 			varchar(50),
  ccb_aml_dose		INT,
  ccb_aml_dosing_unit varchar(50),
  ccb_aml_route		varchar(50),
  ccb_aml_frequency		varchar(50),
  ccb_aml_duration   INT,
  ccb_aml_duration_units  varchar(50),
  ccb_nif				 			varchar(50),
  ccb_nif_dose		INT,
  ccb_nif_dosing_unit varchar(50),
  ccb_nif_route		varchar(50),
  ccb_nif_frequency		varchar(50),
  ccb_nif_duration   INT,
  ccb_nif_duration_units  varchar(50),
  benzathine 					varchar(50) DEFAULT NULL,
  benzathine_dose		INT,
  benzathine_dosing_unit varchar(50),
  benzathine_route		varchar(50),
  benzathine_frequency		varchar(50),
  benzathine_duration   INT,
  benzathine_duration_units  varchar(50),
  other_medications 				varchar(50) DEFAULT NULL,
  took_medications_today 			varchar(50) DEFAULT NULL,
  diet_salt_or_fluid 				varchar(50) DEFAULT NULL,
  mental_health_referral 			varchar(50) DEFAULT NULL,
  palliative_referral 				varchar(50) DEFAULT NULL,
  request_chw_f_u 				varchar(50) DEFAULT NULL,
  next_appointment_date 			date DEFAULT NULL,
  PRIMARY KEY (chf_followup_visit_id)
) ;
