CREATE TABLE mw_pdc_cleft_lip_palate_followup (
  pdc_cleft_lip_palate_visit_id 	int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  weight 				int DEFAULT NULL,
  height				int DEFAULT NULL,
  muac 				int DEFAULT NULL,
  weight_for_age			int DEFAULT NULL,
  height_for_age			int DEFAULT NULL,
  malnutrition				varchar(255) DEFAULT NULL,
  feeding_problems			varchar(255) DEFAULT NULL,
  difficult_breathing			varchar(255) DEFAULT NULL,
  heart_murmur				varchar(255) DEFAULT NULL,
  ear_pain				varchar(255) DEFAULT NULL,
  ear_discharge			varchar(255) DEFAULT NULL,
  other			        varchar(255) DEFAULT NULL,
  surgery_scheduled			varchar(255) DEFAULT NULL,
  surgery_date				date DEFAULT NULL,
  continue_followup			varchar(255) DEFAULT NULL,
  group_therapy			varchar(255) DEFAULT NULL,
  food_supplement			varchar(255) DEFAULT NULL,
  individual_counselling		varchar(255) DEFAULT NULL,
  feeding_counseling			varchar(255) DEFAULT NULL,
  mdat					varchar(255) DEFAULT NULL,
  poser				varchar(255) DEFAULT NULL,
  referred_out				varchar(255) DEFAULT NULL,
  referred_out_specify			varchar(255) DEFAULT NULL,
  if_referred_out			varchar(255) DEFAULT NULL,
  if_referred_out_specify		varchar(255) DEFAULT NULL,
  clinical_plan			varchar(255) DEFAULT NULL,
  next_appointment_date		date DEFAULT NULL,
  PRIMARY KEY (pdc_cleft_lip_palate_visit_id)
) ;
