
CREATE TABLE mw_pdc_trisomy_21_followup (
  pdc_trisomy_21_visit_id 		int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  weight 				int DEFAULT NULL,
  height				int DEFAULT NULL,
  muac 					int DEFAULT NULL,
  malnutrition				varchar(255) DEFAULT NULL,
  passage_normal			varchar(255) DEFAULT NULL,
  diarrhea_persistent			varchar(255) DEFAULT NULL,
  vomiting				varchar(255) DEFAULT NULL,
  ear_pain				varchar(255) DEFAULT NULL,
  ear_discharge				varchar(255) DEFAULT NULL,
  sleep_apnea				varchar(255) DEFAULT NULL,
  sleep_chocking			varchar(255) DEFAULT NULL,
  extremities_pain			varchar(255) DEFAULT NULL,
  extremities_weakness			varchar(255) DEFAULT NULL,
  anticonvulsant			varchar(255) DEFAULT NULL,
  drug_and_dose				varchar(255) DEFAULT NULL,
  adjust_dose				varchar(255) DEFAULT NULL,
  individual_counselling		varchar(255) DEFAULT NULL,
  feeding_counselling			varchar(255) DEFAULT NULL,
  continue_followup			varchar(255) DEFAULT NULL,
  physiotherapy				varchar(255) DEFAULT NULL,
  group_counselling_and_play_therapy	varchar(255) DEFAULT NULL,
  mdat					varchar(255) DEFAULT NULL,
  referred_to_poser			varchar(255) DEFAULT NULL,
  referred_out				varchar(255) DEFAULT NULL,
  referred_out_specify			varchar(255) DEFAULT NULL,
  if_referred_out			varchar(255) DEFAULT NULL,
  if_referred_out_specify		varchar(255) DEFAULT NULL,
  next_appointment_date 		date DEFAULT NULL,
  PRIMARY KEY (pdc_trisomy_21_visit_id )
) ;
