CREATE TABLE mw_pdc_other_diagnosis_followup (
  pdc_other_diagnosis_visit_id 		int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  age_adjusted				int DEFAULT NULL,
  age_non_adjusted			int DEFAULT NULL,
  weight 				int DEFAULT NULL,
  height				int DEFAULT NULL,
  muac 					int DEFAULT NULL,
  weight_against_age			int DEFAULT NULL,
  weight_against_height			int DEFAULT NULL,
  complications_since_last_visit	varchar(255) DEFAULT NULL,
  malnutrition				varchar(255) DEFAULT NULL,
  head_circumference			int DEFAULT NULL,
  convulsions_any_since_last_visit	varchar(255) DEFAULT NULL,
  anticonvulsant			varchar(255) DEFAULT NULL,
  drug_and_dose				varchar(255) DEFAULT NULL,
  adjust_dose				varchar(255) DEFAULT NULL,
  poor_suck				varchar(255) DEFAULT NULL,
  refs_to_feed				varchar(255) DEFAULT NULL,
  less_feed_concerns			varchar(255) DEFAULT NULL,
  individual_counseling			varchar(255) DEFAULT NULL, 
  feeding_counseling			varchar(255) DEFAULT NULL,
  group_counselling			varchar(255) DEFAULT NULL,
  play_therapy				varchar(255) DEFAULT NULL,
  continue_followup			varchar(255) DEFAULT NULL,
  physiotherapy				varchar(255) DEFAULT NULL,
  poser					varchar(255) DEFAULT NULL,
  referred_out				varchar(255) DEFAULT NULL,
  referred_out_specify			varchar(255) DEFAULT NULL,
  if_referred_out			varchar(255) DEFAULT NULL,
  if_referred_out_specify		varchar(255) DEFAULT NULL,
  mdat					varchar(255) DEFAULT NULL,
  plan					varchar(255) DEFAULT NULL,
  next_appointment_date 		date DEFAULT NULL,
  PRIMARY KEY (pdc_other_diagnosis_visit_id)
) ;
