CREATE TABLE mw_poc (
    poc_visit_id INT NOT NULL AUTO_INCREMENT,
    patient_id INT NOT NULL,
    visit_date DATE,
    location VARCHAR(255),
    sample_taken_for_viral_load VARCHAR(255),
    lower_than_detection_limit VARCHAR(255),
    reason_for_testing VARCHAR(255),
    lab_location VARCHAR(255),
    less_than_limit VARCHAR(255),
    reason_for_no_result VARCHAR(255),
    viral_load_sample_id VARCHAR(255),
    reason_for_no_sample VARCHAR(255),
    lab_id VARCHAR(255),
    symptom_present VARCHAR(255),
    symptom_absent VARCHAR(255),
    adherence_session_number VARCHAR(255),
    name_of_support_provider VARCHAR(255),
    number_of_missed_medication_doses_in_past_week VARCHAR(255),
    viral_load_counseling VARCHAR(255),
    medication_adherence_percent VARCHAR(255),
    adherence_counselling VARCHAR(255),
    date_of_blood_sample DATE,
    hiv_test_type VARCHAR(255),
    reason_for_no_sample_eid VARCHAR(255),
    result_of_hiv_test VARCHAR(255),
    hiv_test_time_period VARCHAR(255),
    age VARCHAR(13),
    units_of_age_of_child VARCHAR(255),
    lab_test_serial_number VARCHAR(255),
    date_of_returned_result VARCHAR(255),
    date_result_to_guardian DATE,
    reason_for_testing_coded VARCHAR(255),
    height DECIMAL(10,2),
    is_patient_preg VARCHAR(255),
    muac VARCHAR(255),
    weight DECIMAL(10,2),
    diastolic_blood_pressure DECIMAL(10,2),
    pulse DECIMAL(10,2),
    systolic_blood_pressure DECIMAL(10,2),
    result_of_hiv_test_htc VARCHAR(255),
    hiv_test_type_htc VARCHAR(255),
    colposcopy_of_cervix_with_acetic_acid VARCHAR(255),
    appointment_date DATE,
    qualitative_time VARCHAR(255),
    outcome VARCHAR(255),
    clinical_impression_comments VARCHAR(300),
    refer_to_screening_station VARCHAR(255),
    transfer_out_to VARCHAR(255),
    reason_to_stop_care VARCHAR(255),
    PRIMARY KEY (poc_visit_id)
);
