CREATE TABLE mw_sickle_cell_disease_initial (
  sickle_cell_disease__initial_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  diagnosis_date	 		date DEFAULT NULL,
  microscopy				varchar(255) DEFAULT NULL,
  microscopy_test_date 			date DEFAULT NULL,
  rapid_test				varchar(255) DEFAULT NULL,
  rapid_test_date 			date DEFAULT NULL,
  hb_electrophoresis			varchar(255) DEFAULT NULL,
  hb_electrophoresis_test_date 		date DEFAULT NULL,
  hiv_status 				varchar(255) DEFAULT NULL,
  hiv_test_date 			date DEFAULT NULL,
  art_start_date 			date DEFAULT NULL,
  parent 				varchar(255) DEFAULT NULL,
  sibling				varchar(255) DEFAULT NULL,
  referral_history_inpatient 		varchar(255) DEFAULT NULL,
  referral_history_ic3 			varchar(255) DEFAULT NULL,
  referral_history_opd 			varchar(255) DEFAULT NULL,
  referral_history_other 		varchar(255) DEFAULT NULL,
  referral_history_other_specify 	varchar(255) DEFAULT NULL,
  PRIMARY KEY (sickle_cell_disease__initial_visit_id)
);
