CREATE TABLE mw_sickle_cell_disease_followup (
  sickle_cell_disease_followup_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id 				int NOT NULL,
  visit_date 				date DEFAULT NULL,
  location 				varchar(255) DEFAULT NULL,
  height 				int DEFAULT NULL,
  weight 				int DEFAULT NULL,
  bmi_muac				int DEFAULT NULL,
  bp_systolic 				int DEFAULT NULL,
  bp_diastolic		 		int DEFAULT NULL,
  hr			 		int DEFAULT NULL,
  spo2				 	int DEFAULT NULL,
  temperature				int DEFAULT NULL,
  hospitalized_since_last_visit		varchar(255) DEFAULT NULL,
  absence_from_school 			varchar(255) DEFAULT NULL,
  pain		 			varchar(255) DEFAULT NULL,
  fever		 			varchar(255) DEFAULT NULL,
  medication_rx				varchar(255) DEFAULT NULL,
  antibiotics_rx			varchar(255) DEFAULT NULL,
  medication_side_effects		varchar(255) DEFAULT NULL,
  Jaundice			 	varchar(255) DEFAULT NULL,
  irregular_conjunctiva 		varchar(255) DEFAULT NULL,
  abnormal_lungs_exam 			varchar(255) DEFAULT NULL,
  ascites	 			varchar(255) DEFAULT NULL,
  enlarged_liver 			varchar(255) DEFAULT NULL,
  enlarged_spleen			varchar(255) DEFAULT NULL,
  next_appointment_date			date,
  PRIMARY KEY (sickle_cell_disease_followup_visit_id));
