CREATE TABLE mw_teen_club_intake_survey (
  teen_club_intake_surevy_visit_id int NOT NULL AUTO_INCREMENT,
  patient_id int NOT NULL,
  visit_date date DEFAULT NULL,
  location varchar(255) DEFAULT NULL,
  interview_date date DEFAULT NULL,
  interviewer_name varchar(255),
  village_name varchar(255),
  health_facility varchar(255),
  gender varchar(10),
  literate varchar(10),
  in_school varchar(10),
  dropout_class varchar(255),
  current_class varchar(255),
  plans_after_school varchar(255),
  primary_guardian varchar(255),
  parents_location varchar(255),
  staying_with_single_paren_reason varchar(255),
  num_of_household_members int,
  radio varchar(255),
  television varchar(255),
  mobile_phone varchar(255),
  fridge varchar(255),
  bicycle varchar(255),
  motorcycle varchar(255),
  animal_drawn_cart varchar(255),
  car varchar(255),
  source_of_lighting varchar(255),
  source_of_drinking_water varchar(255),
  toilet_at_home varchar(255),
  kind_of_toilet varchar(255),
  cooking_fuel varchar(255),
  type_of_house_floor varchar(255), 
  type_of_house_roof varchar(255), 
  enrolled_in_teen_club varchar(255),
  teen_club_purpose varchar(255),
  teen_club_activities varchar(255),
  teen_club_topics varchar(255),
  happy_with_teen_club varchar(255),
  social_support_from_teen_club varchar(255),
  kind_of_teen_club_social_support varchar(255),
  like_most varchar(255), 
  rate_social_support varchar(255),
  rate_changes_from_social_support varchar(255),
  challenges_in_daily_life varchar(255),
  can_a_healthy_person_have_hiv varchar(255),
  should_a_positive_student_be_allowed_at_your_school varchar(255),
  is_hiv_a_punishment varchar(255),
  is_hiv_bad_luck varchar(255), 
  can_an_hiv_person_live_longer varchar(255),
  are_people_afraid_to_be_around_you varchar(255),
  injectable_drugs varchar(255),
  ever_used_elicit_drugs varchar(255),
  have_sex_under_alcohol_influence varchar(255),
  have_sex_in_exchange_for_money varchar(255),
  have_sex_with_someone_older_or_younger varchar(255),
  have_you_started_thinking_about_your_future varchar(255),
  career_after_school varchar(255),
  area_of_study_interest varchar(255),
  involed_in_extra_curricular_activities varchar(255),
  extracurricular_activities varchar(255),
  careers_or_industries_interested varchar(255),
  have_role_models varchar(255),
  role_models varchar(255),
  what_kind_of_teen_club_support varchar(255),
  got_vocational_training varchar(255),
  what_do_you_want_to_do varchar(255),
  what_exactly_do_you_want_to_do varchar(255),
  staying_with_single_parent_reason varchar(255),
  can_hiv_be_cured varchar(255),
  how_is_hiv_prevented varchar(255),
  how_is_hiv_transmitted varchar(255),
  rate_your_hiv_knowledge varchar(255),
  PRIMARY KEY (teen_club_intake_surevy_visit_id)
);